"""empty message

Revision ID: 05e96964ced5
Revises: 6fec0f8ce599
Create Date: 2018-01-06 23:55:32.619771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e96964ced5'
down_revision = '6fec0f8ce599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge')
    # ### end Alembic commands ###
