"""empty message

Revision ID: 6fec0f8ce599
Revises: b6841da4606b
Create Date: 2017-12-14 23:55:38.577432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fec0f8ce599'
down_revision = 'b6841da4606b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flickr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('picture', sa.String(length=1000), nullable=True),
    sa.Column('flickr_id', sa.String(length=1000), nullable=True),
    sa.Column('follower', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pinned_flickr',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flickr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flickr_id'], ['flickr.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinned_flickr')
    op.drop_table('flickr')
    # ### end Alembic commands ###
