"""empty message

Revision ID: 73b5832424a0
Revises: 05e96964ced5
Create Date: 2018-01-07 00:03:39.004509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b5832424a0'
down_revision = '05e96964ced5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('badge_id', sa.Integer(), nullable=True))
    op.add_column('badge', sa.Column('catagory', sa.String(length=1000), nullable=True))
    op.add_column('badge', sa.Column('country', sa.String(length=1000), nullable=True))
    op.add_column('badge', sa.Column('month', sa.String(length=1000), nullable=True))
    op.add_column('badge', sa.Column('name', sa.String(length=1000), nullable=True))
    op.add_column('badge', sa.Column('title', sa.String(length=1000), nullable=True))
    op.add_column('badge', sa.Column('year', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge', 'year')
    op.drop_column('badge', 'title')
    op.drop_column('badge', 'name')
    op.drop_column('badge', 'month')
    op.drop_column('badge', 'country')
    op.drop_column('badge', 'catagory')
    op.drop_column('badge', 'badge_id')
    # ### end Alembic commands ###
